-- Video cue: "These five tables match the five entities in my diagram.
-- The links between tables keep bookings tied to real students and slots."
-- H2 SQL. Fixed one-hour slots on whole-hour boundaries, in campus local time.
CREATE TABLE users (
 user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 full_name VARCHAR(100) NOT NULL,
 email VARCHAR(200) NOT NULL UNIQUE,
 password_hash VARCHAR(255), -- Login is deferred; seed accounts cannot authenticate.
 role VARCHAR(10) NOT NULL CHECK (role IN ('CUSTOMER','PROVIDER'))
);
CREATE TABLE providers (
 provider_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id BIGINT NOT NULL UNIQUE REFERENCES users(user_id),
 bio VARCHAR(500) NOT NULL
);
CREATE TABLE services (
 service_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name VARCHAR(100) NOT NULL UNIQUE,
 description VARCHAR(500) NOT NULL
);
CREATE TABLE availability_slots (
 slot_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 provider_id BIGINT NOT NULL REFERENCES providers(provider_id),
 service_id BIGINT NOT NULL REFERENCES services(service_id),
 starts_at TIMESTAMP NOT NULL,
 ends_at TIMESTAMP NOT NULL,
 CONSTRAINT uq_provider_start UNIQUE(provider_id, starts_at),
 CONSTRAINT ck_whole_hour CHECK (starts_at = DATE_TRUNC('HOUR', starts_at)),
 CONSTRAINT ck_one_hour CHECK (ends_at = DATEADD('HOUR', 1, starts_at))
);
CREATE TABLE appointments (
 appointment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 customer_id BIGINT NOT NULL REFERENCES users(user_id),
 slot_id BIGINT NOT NULL REFERENCES availability_slots(slot_id),
 status VARCHAR(10) NOT NULL CHECK(status IN ('BOOKED','CANCELLED')),
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 active_slot_id BIGINT GENERATED ALWAYS AS
   (CASE WHEN status = 'BOOKED' THEN slot_id ELSE NULL END),
 CONSTRAINT uq_active_booking UNIQUE(active_slot_id)
);
-- Video cue: "For a BOOKED row, active_slot_id is its slot ID. The UNIQUE rule
-- rejects a second booking for that slot. For CANCELLED it is empty, so the
-- history remains but the slot can be booked again."
-- H2 permits multiple NULLs in a UNIQUE column: cancellation frees a slot
-- without deleting appointment history. Concurrent BOOKED inserts cannot both win.
